-- 1. 지역별 부서의 수를 조회한다. (부서가 없으면 부서의 수는 0으로 조회한다.)
SELECT l.CITY
		 , COUNT(d.DEPARTMENT_NAME) AS DEP_COUNT
	FROM LOCATIONS l
	LEFT OUTER JOIN DEPARTMENTS d
		ON l.LOCATION_ID = d.LOCATION_ID
 GROUP BY l.CITY
;

SELECT l.CITY
		 , (SELECT COUNT(*)
		 			FROM DEPARTMENTS d
		 		 WHERE d.LOCATION_ID  = l.LOCATION_ID) AS DEP_COUNT
	FROM LOCATIONS l
 ORDER BY DEP_COUNT DESC
;

-- 2. 지역별 사원의 평균월급을 조회한다. (사원이 없으면 평균월급은 0으로 조회한다.)
SELECT l.CITY
		 , NVL(ROUND(AVG(e.SALARY), 1) , 0) AS CITY_AVG_SALARY
	FROM LOCATIONS l
	LEFT OUTER JOIN DEPARTMENTS d 
		ON l.LOCATION_ID = d.LOCATION_ID
	LEFT OUTER JOIN EMPLOYEES e
		ON d.DEPARTMENT_ID = e.DEPARTMENT_ID 
	GROUP BY l.CITY
;

-- 3. 도시명 별 사원의 수를 도시명으로 오름차순 정렬하여 조회한다.(사원이 없으면 사원의 수는 0으로 조회한다.)
SELECT l.CITY
		 , COUNT(e.EMPLOYEE_ID)
	FROM LOCATIONS l
	LEFT OUTER JOIN DEPARTMENTS d 
		ON l.LOCATION_ID = d.LOCATION_ID
	LEFT OUTER JOIN EMPLOYEES e
		ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
 GROUP BY l.CITY
 ORDER BY l.CITY ASC
;

-- 4. 모든 사원들의 현재 직무명과 과거의 직무명을 조회한다. 만약 직무가 한번도 변경되지 않았다면, 과거의 직무명은 '없음' 으로 조회한다.
SELECT e.EMPLOYEE_ID AS EMP_ID
		 , j_cur.JOB_TITLE AS CURRENT_JOB_TITLE
		 , NVL(j_past.JOB_TITLE, '없음') AS PAST_JOB_TITLE
	FROM EMPLOYEES e
 INNER JOIN JOBS j_cur 
 		ON e.JOB_ID = j_cur.JOB_ID
	LEFT OUTER JOIN JOB_HISTORY jh
		ON e.EMPLOYEE_ID = jh.EMPLOYEE_ID
	LEFT OUTER JOIN JOBS j_past
		ON jh.JOB_ID = j_past.JOB_ID 
 ORDER BY e.EMPLOYEE_ID ASC
;	

