-- 1. 모든 부서들의 정보와 도시 정보를 조회한다. 27
SELECT d.DEPARTMENT_ID
		 , d.DEPARTMENT_NAME
		 , d.MANAGER_ID
		 , d.LOCATION_ID
		 , l.STREET_ADDRESS
		 , l.POSTAL_CODE
		 , l.CITY
		 , l.STATE_PROVINCE
		 , l.COUNTRY_ID 
	FROM DEPARTMENTS d
 INNER JOIN LOCATIONS l
 		ON d.LOCATION_ID = l.LOCATION_ID 
;

-- 2. 모든 사원들의 정보와 부서명을 조회한다. 106
SELECT e.EMPLOYEE_ID
     , e.FIRST_NAME
     , e.LAST_NAME
     , e.EMAIL
     , e.PHONE_NUMBER
     , e.HIRE_DATE
     , e.JOB_ID
     , e.SALARY
     , e.COMMISSION_PCT
     , e.MANAGER_ID
     , e.DEPARTMENT_ID
     , d.DEPARTMENT_NAME
	FROM EMPLOYEES e
 INNER JOIN DEPARTMENTS d
 		ON e.DEPARTMENT_ID = d.DEPARTMENT_ID 
;

-- 3. 111번 사원의 모든 정보와 부서명을 조회한다. 1
SELECT e.EMPLOYEE_ID
     , e.FIRST_NAME
     , e.LAST_NAME
     , e.EMAIL
     , e.PHONE_NUMBER
     , e.HIRE_DATE
     , e.JOB_ID
     , e.SALARY
     , e.COMMISSION_PCT
     , e.MANAGER_ID
     , e.DEPARTMENT_ID
     , d.DEPARTMENT_NAME
	FROM EMPLOYEES e
 INNER JOIN DEPARTMENTS d
		ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
 WHERE e.EMPLOYEE_ID = 111
;
 
-- 4. 115번의 사원의 모든 정보와 부서명, 직무명을 조회한다. 1
SELECT e.EMPLOYEE_ID
     , e.FIRST_NAME
     , e.LAST_NAME
     , e.EMAIL
     , e.PHONE_NUMBER
     , e.HIRE_DATE
     , e.JOB_ID
     , e.SALARY
     , e.COMMISSION_PCT
     , e.MANAGER_ID
     , e.DEPARTMENT_ID
     , d.DEPARTMENT_NAME
     , j.JOB_ID
	FROM EMPLOYEES e
 INNER JOIN DEPARTMENTS d
		ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
 INNER JOIN JOBS j
 		ON e.JOB_ID = j.JOB_ID 
 WHERE e.EMPLOYEE_ID = 115
;

-- 5. 100번 사원의 모든 정보와 부서명, 직무명, 도시명을 조회한다. 1
SELECT e.EMPLOYEE_ID
     , e.FIRST_NAME
     , e.LAST_NAME
     , e.EMAIL
     , e.PHONE_NUMBER
     , e.HIRE_DATE
     , e.JOB_ID
     , e.SALARY
     , e.COMMISSION_PCT
     , e.MANAGER_ID
     , e.DEPARTMENT_ID
     , d.DEPARTMENT_NAME
     , j.JOB_ID
     , l.CITY
	FROM EMPLOYEES e
 INNER JOIN DEPARTMENTS d
		ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
 INNER JOIN LOCATIONS l
 		ON d.LOCATION_ID = l.LOCATION_ID
 INNER JOIN JOBS j
 		ON e.JOB_ID = j.JOB_ID
 WHERE e.EMPLOYEE_ID = 100
;

-- 6. 부서명별 사원의 수를 조회한다. 11
SELECT d.DEPARTMENT_NAME
		 , COUNT(EMPLOYEE_ID)
	FROM EMPLOYEES e
 INNER JOIN DEPARTMENTS d
 		ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
 GROUP BY d.DEPARTMENT_NAME
;

-- 7. 직무명별 사원의 평균월급을 조회한다. 19
SELECT j.JOB_TITLE
		 , ROUND(AVG(e.SALARY), 1) AS 평균월급
	FROM EMPLOYEES e
 INNER JOIN JOBS j
 		ON e.JOB_ID = j.JOB_ID
 GROUP BY j.JOB_TITLE
;

-- 8. 부서명, 직무명별 사원의 수와 평균월급을 조회한다. 19
SELECT d.DEPARTMENT_NAME		 
		 , COUNT(e.EMPLOYEE_ID) AS 사원수
		 , j.JOB_TITLE
		 , ROUND(AVG(e.SALARY), 1) AS 평균월급
	FROM EMPLOYEES e
 INNER JOIN DEPARTMENTS d
 		ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
 INNER JOIN JOBS j
 		ON e.JOB_ID = j.JOB_ID
 GROUP BY d.DEPARTMENT_NAME
 				, j.JOB_TITLE
;

-- 9. 부서명별 평균월급을 부서명으로 내림차순 정렬하여 조회한다. 11
SELECT d.DEPARTMENT_NAME
		 , ROUND(AVG(e.SALARY), 1)
	FROM EMPLOYEES e
 INNER JOIN DEPARTMENTS d
 		ON e.DEPARTMENT_ID = d.DEPARTMENT_ID 
 GROUP BY d.DEPARTMENT_NAME
 ORDER BY d.DEPARTMENT_NAME DESC
;

-- 10. 부서명별 최고월급을 최고월급으로 오름차순 정렬하여 조회한다. 11
SELECT d.DEPARTMENT_NAME
		 , MAX(e.SALARY)
	FROM EMPLOYEES e
 INNER JOIN DEPARTMENTS d
 		ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
 GROUP BY d.DEPARTMENT_NAME
 ORDER BY MAX(e.SALARY) ASC
;

-- 11. 도시명 별 사원의 수를 도시명으로 오름차순 정렬하여 조회한다. 7
SELECT l.CITY
		 , COUNT(e.EMPLOYEE_ID) AS 사원수
	FROM EMPLOYEES e
 INNER JOIN DEPARTMENTS d
 		ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
 INNER JOIN LOCATIONS l
 		ON d.LOCATION_ID = l.LOCATION_ID
 GROUP BY l.CITY 
 ORDER BY l.CITY ASC
;

-- 12. 도시별 부서의 수를 조회한다. 7
SELECT l.CITY
		 , COUNT(d.DEPARTMENT_ID)
	FROM DEPARTMENTS d
 INNER JOIN LOCATIONS l
 		ON d.LOCATION_ID = l.LOCATION_ID
 GROUP BY l.CITY
;

-- 13. 도시별 사원의 평균월급을 조회한다. 7
SELECT l.CITY
		 , ROUND(AVG(e.SALARY), 1) AS 평균월급
	FROM EMPLOYEES e
 INNER JOIN DEPARTMENTS d
 		ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
 INNER JOIN LOCATIONS l
 		ON d.LOCATION_ID = l.LOCATION_ID
 GROUP BY l.CITY
;
